# arxivの学問領域の指定
subject: 'cat:q-bio.*'

# 検索キーワード
keywords:
        demethylation: 2
        regeneration: 3
        planaria: 5
        flatworm: 4
        whole-body regeneration: 5
        neoblast: 1
        HRJD: 10
        Jmjc: 3

# 通知の閾値
score_threshold: 3
